//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceClientTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SomeExampleDataContract", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceTest")]
    [System.SerializableAttribute()]
    public partial class SomeExampleDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetJsonData", ReplyAction="http://tempuri.org/IMyService/GetJsonDataResponse")]
        string GetJsonData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetJsonData", ReplyAction="http://tempuri.org/IMyService/GetJsonDataResponse")]
        System.Threading.Tasks.Task<string> GetJsonDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetXmlData", ReplyAction="http://tempuri.org/IMyService/GetXmlDataResponse")]
        string GetXmlData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetXmlData", ReplyAction="http://tempuri.org/IMyService/GetXmlDataResponse")]
        System.Threading.Tasks.Task<string> GetXmlDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDefaultObject", ReplyAction="http://tempuri.org/IMyService/GetDefaultObjectResponse")]
        WCFServiceClientTest.ServiceReference1.SomeExampleDataContract GetDefaultObject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDefaultObject", ReplyAction="http://tempuri.org/IMyService/GetDefaultObjectResponse")]
        System.Threading.Tasks.Task<WCFServiceClientTest.ServiceReference1.SomeExampleDataContract> GetDefaultObjectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyService/GetDataUsingDataContractResponse")]
        WCFServiceClientTest.ServiceReference1.SomeExampleDataContract GetDataUsingDataContract(WCFServiceClientTest.ServiceReference1.SomeExampleDataContract composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCFServiceClientTest.ServiceReference1.SomeExampleDataContract> GetDataUsingDataContractAsync(WCFServiceClientTest.ServiceReference1.SomeExampleDataContract composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : WCFServiceClientTest.ServiceReference1.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<WCFServiceClientTest.ServiceReference1.IMyService>, WCFServiceClientTest.ServiceReference1.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetJsonData(string value) {
            return base.Channel.GetJsonData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetJsonDataAsync(string value) {
            return base.Channel.GetJsonDataAsync(value);
        }
        
        public string GetXmlData(string value) {
            return base.Channel.GetXmlData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetXmlDataAsync(string value) {
            return base.Channel.GetXmlDataAsync(value);
        }
        
        public WCFServiceClientTest.ServiceReference1.SomeExampleDataContract GetDefaultObject() {
            return base.Channel.GetDefaultObject();
        }
        
        public System.Threading.Tasks.Task<WCFServiceClientTest.ServiceReference1.SomeExampleDataContract> GetDefaultObjectAsync() {
            return base.Channel.GetDefaultObjectAsync();
        }
        
        public WCFServiceClientTest.ServiceReference1.SomeExampleDataContract GetDataUsingDataContract(WCFServiceClientTest.ServiceReference1.SomeExampleDataContract composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WCFServiceClientTest.ServiceReference1.SomeExampleDataContract> GetDataUsingDataContractAsync(WCFServiceClientTest.ServiceReference1.SomeExampleDataContract composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
